### ISSUE TITLE
Add option for full paths

### ISSUE THREAD

**Issue by mikebranski** [DanielGarcia-Carrillo/autocomplete-js-import#37]
It would be really nice to have an option to use the full project path in an import. With fuzzy matching enabled, typing `FooMod` might show `src/app/foo-mod/index.js` in the search results dropdown, but selecting it always converts it to a path relative to the current file.

While this works, we use absolute(-ish) paths in conjunction with babelify and aliasify and, I think, the relative paths defeat that.

**Comment by jesselee34** [comment]
I implemented and created a pull request.

https://github.com/DanielGarcia-Carrillo/autocomplete-js-import/pull/38

**Comment by DanielGarcia-Carrillo** [comment]
Released in [v1.4](https://github.com/DanielGarcia-Carrillo/autocomplete-js-import/releases/tag/v1.4.0)
